### ISSUE TITLE
Backend return field-level errors that can be parsed into user-friendly error messages

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_backend_prototype#139]
Update backend error handling to return field-level errors as an object instead of as an array
Hash can be property + error message
Have a special one for page-level for errors that are not related to one field

**Comment by jupiter007** [comment]
Moving this to status `Next Sprint`, since we talked about doing some updates to the backend error messaging structure

**Comment by briri** [comment]
@jupiter007 what do you think of the following:
```
{
  "id": 123,
  "title": "My Test Project",
  "abstractTest": "Lorem ipsum ...",
  "someRequiredField": null,
  "startDate": "2025-01-30",
  "endDate": "2024-12-31",
  "errors": {
    "domeRequiredField": "Field can't be blank",
    "endDate": "End date must come after the start date",
    "global": ["A project with that title already exists"]
  }  
}
```

An object's `errors` property would be an object rather than and array. The `global` entry would be reserved for non-property specific errors.

**Comment by jupiter007** [comment]
> [@jupiter007](https://github.com/jupiter007) what do you think of the following:
> 
> ```
> {
>   "id": 123,
>   "title": "My Test Project",
>   "abstractTest": "Lorem ipsum ...",
>   "someRequiredField": null,
>   "startDate": "2025-01-30",
>   "endDate": "2024-12-31",
>   "errors": {
>     "someRequiredField": "Field can't be blank",
>     "endDate": "End date must come after the start date",
>     "global": ["A project with that title already exists"]
>   }  
> }
> ```
> 
> An object's `errors` property would be an object rather than and array. The `global` entry would be reserved for non-property specific errors.

That looks good to me Brian. I can't think of any issues we'd have with that. However, wouldn't global errors also be returned as part of the graphql `errors` response?

**Comment by briri** [comment]
Ah, I should have clarified that.

GraphQL errors would still come back as they do now for things like `Bad Request`, `Not Found`, `Server Error`, `Unauthorized`, etc. that have a related HTTP status code.

I was thinking the `global` array would contain messages that aren't specific to an individual property. I used "already exists" above and can't really think of any others at the moment. Would it be better to call it something other than `global`?

**Comment by jupiter007** [comment]
`global` does make it sound like it's across multiple pages. Maybe we could use `general`? For a GraphQL error like `Bad User Input`, it seems like it sort of overlaps with field-level errors. For instance, this error:

```
 {
  "errors": [
    {
      "message": "Question text can't be blank",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addQuestion"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "stacktrace": [
          "GraphQLError: Question text can't be blank",
          "    at BadUserInputError (/app/src/utils/graphQLErrors.ts:58:10)",
          "    at Object.addQuestion (/app/src/resolvers/question.ts:66:34)",
          "    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    }
  ],
  "data": null
}
```

So, we might not get any data back, meaning no field-level errors, and just this general graphql user input error.

**Comment by briri** [comment]
Oh interesting. That's an older approach. I guess that's why we have this ticket! 😆 As part of this I will go through all the resolvers/models and make sure they're handling things in the same way.

Ok, I like `general` for that error type. 

I'll make sure the GraphQL errors are only for things the user can't correct and that the nextJS app would want to handle in very specific ways (e.g. Unauthorized -> redirect to the sign in page, Forbidden -> redirect to the prior page with a message, etc.)

**Comment by jupiter007** [comment]
Cool, thanks Brian :)

**Comment by briri** [comment]
The GraphQL errors would be:
- 400 Bad Request - I think maybe Apollo already handles improperly formatted GraphQL queries/mutations but I guess the frontend should treat this like a 500 error maybe so the user's experience is similar
- 401 Unauthorized - token isn't present, the frontend is already handling this I think
- 403 Forbidden - the user doesn't have permission to do the requested query/mutation so frontend would display a canned "You don't have permission to X" message
- 404 Not Found - frontend would redirect to the last page and display a canned "X not found" message 
- 500 Server Error - frontend would redirect to the last page and display a canned "We're sorry message"

**Comment by briri** [comment]
Ok, the final error structure looks like this:

The new field level errors will come through as:
```
{
  "id": null,
  "name": "My new thing",
  "someRequiredField": null,
  "someURL": "thing1",
  "errors": {
    "general": "A thing with that name already exists",
    "someRequiredField": "Some required field can't be blank",
    "someURL": "Invalid URL",
  }
}
```

The backend will also continue to send the normal HTTP errors for the following conditions:
400 - Something was wrong with the GraphQL query/mutation (e.g. requested a field that doesn't exist, missing a required argument, etc.)
401 - The access token is no longer valid (or not present)
403 - The user's role does not provide permission
404 - The record doesn't exist
500 - Catch all for any internal errors within the backend
